// Ducky Demo Action runtime.
//
// Reads inputs from env (mapped by action.yml), renders a demo via the Ducky
// API, and posts the video as a PR comment. When no `task` input is set, the
// PR's title/body/diff are sent to Ducky, which derives what to demo — or says
// there's nothing user-visible to show, in which case the run skips cleanly.
//
// Zero deps: node20 global fetch + the GitHub REST API. The PR comment is posted
// with a JSON body (NOT shell-interpolated) so backticks/newlines aren't mangled.

import { readFileSync } from "node:fs";

const env = process.env;
const fail = (msg) => { console.log(`::error::Ducky: ${msg}`); process.exit(1); };

const KEY = env.DUCKY_API_KEY;
const URL_ = env.RENDER_URL;
let TASK = env.RENDER_TASK;
const REEL = env.RENDER_REEL !== "false"; // default true
const API = (env.DUCKY_API_BASE || "https://api.tryducky.dev").replace(/\/+$/, "");
const PR = env.PR_NUMBER;
const GH_TOKEN = env.GH_TOKEN;
const REPO = env.GH_REPO; // owner/repo

const POLL_INTERVAL_MS = 20_000;
const POLL_MAX = 30; // ~10 min cap
const DONE = ["done", "succeeded", "completed"];
const TERMINAL = [...DONE, "failed", "error", "cancelled"];

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

// No `task` input → derive one from the PR. Title/body come free from the
// event payload on disk; the diff is one GitHub API call. Ducky's server
// decides whether the change is user-visible — if not, skip cleanly (exit 0,
// no render, no comment).
async function deriveTask() {
  let title, body;
  try {
    const event = JSON.parse(readFileSync(env.GITHUB_EVENT_PATH, "utf8"));
    title = event.pull_request?.title;
    body = event.pull_request?.body || undefined;
  } catch {
    /* fall through to the title check */
  }
  if (!title) fail("no task input and no PR in the event payload — set `task`, or run on a pull_request event.");

  const diffRes = await fetch(`https://api.github.com/repos/${REPO}/pulls/${PR}`, {
    headers: {
      Authorization: `Bearer ${GH_TOKEN}`,
      Accept: "application/vnd.github.diff",
      "X-GitHub-Api-Version": "2022-11-28",
    },
  });
  if (!diffRes.ok) fail(`fetching the PR diff failed (${diffRes.status})`);
  const diff = (await diffRes.text()).slice(0, 6_000);

  console.log("Ducky: no task set — deriving one from the PR");
  const res = await fetch(`${API}/v1/derive`, {
    method: "POST",
    headers: { Authorization: `Bearer ${KEY}`, "content-type": "application/json" },
    body: JSON.stringify({ title: title.slice(0, 300), body: body?.slice(0, 10_000), diff, url: URL_ }),
  });
  if (!res.ok) fail(`task derivation failed (${res.status}): ${(await res.text()).slice(0, 300)}`);
  const verdict = await res.json();
  if (!verdict.demoable) {
    console.log(`Ducky: nothing user-visible to demo in this PR — skipping. (${verdict.reason ?? "no reason given"})`);
    process.exit(0);
  }
  console.log(`Ducky: derived task — ${verdict.task}`);
  return verdict.task;
}

async function main() {
  for (const [k, v] of [["api-key", KEY], ["url", URL_]]) {
    if (!v) fail(`missing required input: ${k}`);
  }
  if (!PR) fail("no pull request in context — run this action on a PR event so it can comment.");
  if (!TASK) TASK = await deriveTask();

  // 1) submit the render
  console.log(`Ducky: rendering ${URL_}`);
  const subRes = await fetch(`${API}/v1/renders`, {
    method: "POST",
    headers: { Authorization: `Bearer ${KEY}`, "content-type": "application/json" },
    body: JSON.stringify({ url: URL_, task: TASK, reel: REEL, source: "github_pr" }),
  });
  if (!subRes.ok) fail(`render submit failed (${subRes.status}): ${(await subRes.text()).slice(0, 300)}`);
  const sub = await subRes.json();
  console.log(`Ducky: render ${sub.id} queued`);

  // 2) poll to a terminal state
  let final = null;
  for (let i = 0; i < POLL_MAX && !final; i++) {
    await sleep(POLL_INTERVAL_MS);
    const r = await (await fetch(`${API}/v1/renders/${sub.id}`, {
      headers: { Authorization: `Bearer ${KEY}` },
    })).json();
    console.log(`Ducky: ${r.status}`);
    if (TERMINAL.includes(r.status)) final = r;
  }
  if (!final) fail("render timed out (>10 min)");
  if (!DONE.includes(final.status)) fail(`render ${final.status}`);
  const video = final.reel_url || final.demo_url;
  if (!video) fail("render finished but produced no video");

  // 3) post the PR comment via the GitHub REST API (JSON body — no shell escaping)
  const body = [
    "🦆 **Ducky — demo of this change**",
    "",
    `**Task:** ${TASK}`,
    "",
    `▶️ **[Watch the demo](${video})**`,
    "",
    '<sub>Auto-generated by <a href="https://tryducky.dev">Ducky</a>.</sub>',
  ].join("\n");
  const cRes = await fetch(`https://api.github.com/repos/${REPO}/issues/${PR}/comments`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${GH_TOKEN}`,
      Accept: "application/vnd.github+json",
      "content-type": "application/json",
      "X-GitHub-Api-Version": "2022-11-28",
    },
    body: JSON.stringify({ body }),
  });
  if (!cRes.ok) {
    fail(`posting the PR comment failed (${cRes.status}): ${(await cRes.text()).slice(0, 200)} — does the workflow grant 'permissions: pull-requests: write'?`);
  }
  console.log(`Ducky: posted demo to PR #${PR}`);
}

main().catch((e) => fail(e?.message ?? String(e)));
